AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mytable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  TodoTableName:
    Value: !Ref TodoTable
    Export:
      Name: TodoTableName
  TodoTableArn:
    Value: !GetAtt TodoTable.Arn
    Export:
      Name: TodoTableArn
